Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('checksheet')->group(function() {
            Route::name('checksheet.')->group(function() {

                Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');

                Route::get('daily', 'Admin\ChecksheetDailyController@index')->name('daily');
                Route::get('daily/data', 'Admin\ChecksheetDailyController@indexData')->name('daily.data');
                Route::get('daily/create', 'Admin\ChecksheetDailyController@create')->name('daily.create');
                Route::post('daily/create', 'Admin\ChecksheetDailyController@store')->name('daily.store');
                Route::get('daily/show', 'Admin\ChecksheetDailyController@show')->name('daily.show');
                Route::get('daily/submit', 'Admin\ChecksheetDailyController@submitForm')->name('daily.submit');
                Route::patch('daily/submit', 'Admin\ChecksheetDailyController@submitSave')->name('daily.submit.save');
                Route::delete('daily/{id}', 'Admin\ChecksheetDailyController@destroy')->name('daily.destroy');
                Route::get('daily/{id}/download', 'Admin\ChecksheetDailyController@download')->name('daily.download');

                Route::get('weekly', 'Admin\ChecksheetWeeklyController@index')->name('weekly');
                Route::get('weekly/data', 'Admin\ChecksheetWeeklyController@indexData')->name('weekly.data');
                Route::get('weekly/create', 'Admin\ChecksheetWeeklyController@create')->name('weekly.create');
                Route::post('weekly/create', 'Admin\ChecksheetWeeklyController@store')->name('weekly.store');
                Route::get('weekly/show', 'Admin\ChecksheetWeeklyController@show')->name('weekly.show');
                Route::get('weekly/submit', 'Admin\ChecksheetWeeklyController@submitForm')->name('weekly.submit');
                Route::patch('weekly/submit', 'Admin\ChecksheetWeeklyController@submitSave')->name('weekly.submit.save');
                Route::delete('weekly/{id}', 'Admin\ChecksheetWeeklyController@destroy')->name('weekly.destroy');
                Route::get('weekly/{id}/download', 'Admin\ChecksheetWeeklyController@download')->name('weekly.download');

                Route::get('approval', 'Admin\ChecksheetApprovalController@index')->name('approval');
                Route::get('approval/data/daily', 'Admin\ChecksheetApprovalController@indexDataDaily')->name('approval.data.daily');
                Route::get('approval/data/weekly', 'Admin\ChecksheetApprovalController@indexDataWeekly')->name('approval.data.weekly');
                Route::get('approval/verify', 'Admin\ChecksheetApprovalController@verifyForm')->name('approval.verify');
                Route::patch('approval/verify', 'Admin\ChecksheetApprovalController@verifySave')->name('approval.verify.save');
                Route::get('approval/reject', 'Admin\ChecksheetApprovalController@rejectForm')->name('approval.reject');
                Route::patch('approval/reject', 'Admin\ChecksheetApprovalController@rejectSave')->name('approval.reject.save');

            });
        });
    });
});

Route::get('reminder/weekly', 'Admin\ChecksheetWeeklyController@reminder')->name('reminder.weekly');
Route::get('reminder/daily', 'Admin\ChecksheetDailyController@reminder')->name('reminder.daily');

// Route::prefix('checksheetmanagement')->group(function() {
//     Route::get('/', 'ChecksheetManagementController@index');
// });

Resources/views/admin/checksheet/approval/index.blade.php
@extends('checksheetmanagement::layouts.master')

@section('content')
    
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Unit Operation Schedule</h3>
                    <div class="box-tools pull-right">
                        @can('checksheet-daily-create')
                        <button class="btn btn-sm btn-primary" id="new-daily">
                            <i class="fa fa-plus"></i> New
                        </button>
                        @endcan
                    </div>
                </div>
                <div class="box-body" style="min-height: 350px">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table id="grid-daily" class="table table-bordered table-striped" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th class="text-center" style="width: 2%">#</th>
                                            <th class="text-center" style="width: 10%">Date</th>
                                            <th class="text-center">Test</th>
                                            <th class="text-center" style="width: 15%">Status</th>
                                            <th class="text-center" style="width: 5%"><i class="fa fa-navicon"></i></th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="modal-box" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal-box">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div id="content"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Pengecekan Plant</h3>
                    <div class="box-tools pull-right">
                        @can('checksheet-weekly-create')
                        <button class="btn btn-sm btn-primary" id="new-weekly">
                            <i class="fa fa-plus"></i> New
                        </button>
                        @endcan
                    </div>
                </div>
                <div class="box-body" style="min-height: 350px">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table id="grid-weekly" class="table table-bordered table-striped" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th class="text-center" style="width: 2%">#</th>
                                            <th class="text-center" style="width: 10%">Date</th>
                                            <th class="text-center">Test</th>
                                            <th class="text-center" style="width: 15%">Status</th>
                                            <th class="text-center" style="width: 5%"><i class="fa fa-navicon"></i></th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $('#new-daily').on('click', function() {
                $.ajax({
                    type: "GET",
                    url: "{!! route('checksheet.daily.create') !!}",
                    success: function(data) {
                        $('#modal-box').modal('toggle');
                        $('#content').html(data);
                    }
                });
            });
            $('#new-weekly').on('click', function() {
                $.ajax({
                    type: "GET",
                    url: "{!! route('checksheet.weekly.create') !!}",
                    success: function(data) {
                        $('#modal-box').modal('toggle');
                        $('#content').html(data);
                    }
                });
            });
            var table = $('#grid-daily').DataTable({
                processing: true,
                serverSide: true,
                responsive: false,
                PaginationType: "two_button",
                paginate:true,
                deferRender: true,
                keys: false,
                scrollX: true,
                dom: '<"row"<"col-md-4"l><"col-md-4 text-center"B><"col-md-4"f>>' + 'rtip',
                buttons: [
                    {
                        text: '<i class="fa fa-refresh"></i> Refresh',
                        className: "btn-sm",
                        action: function(e, dt, node, config) {
                            dt.ajax.reload();
                        }
                    }
                ],
                ajax: { 
                    url: "{!! route('checksheet.approval.data.daily') !!}",
                    pages: 10,
                },
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', className: "small", orderable: false, searchable: false},
                    {data: 'date', name: 'date', className: "small"},
                    {data: 'name', name: 'name', className: "small", orderable: false},
                    {data: 'status', name: 'status', className: "small"},
                    {data: 'action', name: 'action', className: "text-center", orderable: false, searchable: false},
                ],
                columnDefs: [
                    {targets: 1, render: $.fn.dataTable.render.moment('YYYY-MM-DD', 'DD-MM-YYYY')},
                ],
                order: [
                    [1, 'desc']
                ],
                language: {
                    processing: "<p class='text-center'>Loading...</p>"
                },
            });
            var table = $('#grid-weekly').DataTable({
                processing: true,
                serverSide: true,
                responsive: false,
                PaginationType: "two_button",
                paginate:true,
                deferRender: true,
                keys: false,
                scrollX: true,
                dom: '<"row"<"col-md-4"l><"col-md-4 text-center"B><"col-md-4"f>>' + 'rtip',
                buttons: [
                    {
                        text: '<i class="fa fa-refresh"></i> Refresh',
                        className: "btn-sm",
                        action: function(e, dt, node, config) {
                            dt.ajax.reload();
                        }
                    }
                ],
                ajax: { 
                    url: "{!! route('checksheet.approval.data.weekly') !!}",
                    pages: 10,
                },
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', className: "small", orderable: false, searchable: false},
                    {data: 'date', name: 'date', className: "small"},
                    {data: 'name', name: 'name', className: "small", orderable: false},
                    {data: 'status', name: 'status', className: "small"},
                    {data: 'action', name: 'action', className: "text-center", orderable: false, searchable: false},
                ],
                columnDefs: [
                    {targets: 1, render: $.fn.dataTable.render.moment('YYYY-MM-DD', 'DD-MM-YYYY')},
                ],
                order: [
                    [1, 'desc']
                ],
                language: {
                    processing: "<p class='text-center'>Loading...</p>"
                },
            });
            $('.dataTables_scrollBody').css('height', '200px');
        });

        function verifyWeekly(id) {
            $.ajax({
                type: "GET",
                url: "{!! route('checksheet.approval.verify') !!}",
                data: {
                    id: id,
                    type: 'W'
                },
                success: function(data) {
                    $('#modal-box').modal('toggle');
                    $('#content').html(data);
                }
            });
        }
    </script>
@endsection

Resources/views/admin/checksheet/approval/reject.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="modal-box">
        @switch($type)
            @case('D')
                Unit Operation Schedule 
                @break
            @case('W')
                Pengecekan Plant
                @break
            @default
                {{ null }}
        @endswitch
        - {{ $data->name }}
    </h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-lg-6">
            <table class="table table-bordered">
                <tr>
                    <th>Name</th>
                    <td>{{ $data->name }}</td>
                </tr>
                <tr>
                    <th>Note</th>
                    <td>{{ $data->note }}</td>
                </tr>
                <tr>
                    <th>Year</th>
                    <td>{{ $data->year }}</td>
                </tr>
                <tr>
                    <th>Week</th>
                    <td>{{ $data->week }}</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>{{ dateFormatDmy($data->date) }}</td>
                </tr>
            </table>
        </div>
        <div class="col-lg-6">
            <table class="table table-bordered">
                <tr>
                    <th>Status</th>
                    <td>{{ getStatusName($data->status) }}</td>
                </tr>
                <tr>
                    <th>Created By</th>
                    <td>
                        {{ isset($data->createdBy->name) ? $data->createdBy->name : null }}
                        <small>({{ $data->created_at }})</small>
                    </td>
                </tr>
                @if(!is_null($data->uploaded_by))
                    <tr>
                        <th>Uploaded By</th>
                        <td>
                            {{ $data->uploadedBy->name }}
                            <small>({{ $data->uploaded_at }})</small>
                        </td>
                    </tr>
                @endif
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @if(isset($ext))
                @if($ext == 'pdf')
                    <embed src="{{ _get_file($data->filename, 'checksheet/' . $path . '/', 'public') }}#toolbar=0" type="application/pdf" style="width: 100%; height: 400px;" />
                @else
                    <img src="{{ _get_file($data->filename, 'checksheet/' . $path . '/', 'public') }}" style="width: 100%" />
                @endif
            @endif
            @can(['checksheet-daily-download','checksheet-weekly-download'])
                <a href="{{ route('checksheet.daily.download', $data->id) }}" class="btn btn-sm btn-info"><i class="fa fa-download"></i> Download</a>
            @endcan
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="note" class="col-sm-2 control-label">Notes</label>
                <div class="col-sm-9">
                    {!! Form::textarea('note', null, [ 'class' => 'form-control input-sm', 'id' => 'note', 'rows' => 3]) !!}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-danger" id="submit"><i class="fa fa-times"></i> Reject</button>
</div>

<script>
    $(document).ready(function() {
        $("#submit").on('click', function(e) {
            let id = "{{ $data->id }}";
            let csrf = "{{ csrf_token() }}";
            let type = "{{ $type }}";
            let note = $("#note").val();
            $.ajax({
                type: "POST",
                url: "{{ route('checksheet.approval.reject.save') }}",
                data: {
                    id: id,
                    type: type,
                    note: note,
                    _token: csrf,
                    _method: "patch"
                },
                success: function(data) {
                    $("#modal-box").modal('hide');
                    toastr.success(data.message);
                    $('#grid-daily').DataTable().ajax.reload(null, false);
                    $('#grid-weekly').DataTable().ajax.reload(null, false);
                },
                error: function(error) {
                    toastr.error(error.message);
                }
            });
        });
    });
</script>

Resources/views/admin/checksheet/approval/show.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="modal-box">
        @switch($type)
            @case('D')
                Unit Operation Schedule 
                @break
            @case('W')
                Pengecekan Plant
                @break
            @default
                {{ null }}
        @endswitch
        - {{ $data->name }}
    </h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-lg-6">
            <table class="table table-bordered">
                <tr>
                    <th>Name</th>
                    <td>{{ $data->name }}</td>
                </tr>
                <tr>
                    <th>Note</th>
                    <td>{{ $data->note }}</td>
                </tr>
                <tr>
                    <th>Year</th>
                    <td>{{ $data->year }}</td>
                </tr>
                <tr>
                    <th>Week</th>
                    <td>{{ $data->week }}</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>{{ dateFormatDmy($data->date) }}</td>
                </tr>
            </table>
        </div>
        <div class="col-lg-6">
            <table class="table table-bordered">
                <tr>
                    <th>Status</th>
                    <td>{{ getStatusName($data->status) }}</td>
                </tr>
                <tr>
                    <th>Created By</th>
                    <td>
                        {{ isset($data->createdBy->name) ? $data->createdBy->name : null }}
                        <small>({{ $data->created_at }})</small>
                    </td>
                </tr>
                @if(!is_null($data->uploaded_by))
                    <tr>
                        <th>Uploaded By</th>
                        <td>
                            {{ $data->uploadedBy->name }}
                            <small>({{ $data->uploaded_at }})</small>
                        </td>
                    </tr>
                @endif
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @if(isset($ext))
                @if($ext == 'pdf')
                    <embed src="{{ _get_file($data->filename, 'checksheet/' . $path . '/', 'public') }}#toolbar=0" type="application/pdf" style="width: 100%; height: 400px;" />
                @else
                    <img src="{{ _get_file($data->filename, 'checksheet/' . $path . '/', 'public') }}" style="width: 100%" />
                @endif
            @endif
            @can(['checksheet-daily-download','checksheet-weekly-download'])
                <a href="{{ route('checksheet.daily.download', $data->id) }}" class="btn btn-sm btn-info"><i class="fa fa-download"></i> Download</a>
            @endcan
        </div>
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-primary" id="submit"><i class="fa fa-check"></i> Verify</button>
</div>

<script>
    $(document).ready(function() {
        $("#submit").on('click', function(e) {
            let id = "{{ $data->id }}";
            let csrf = "{{ csrf_token() }}";
            let type = "{{ $type }}";
            $.ajax({
                type: "POST",
                url: "{{ route('checksheet.approval.verify.save') }}",
                data: {
                    id: id,
                    type: type,
                    _token: csrf,
                    _method: "patch"
                },
                success: function(data) {
                    $("#modal-box").modal('hide');
                    toastr.success(data.message);
                    $('#grid-daily').DataTable().ajax.reload(null, false);
                    $('#grid-weekly').DataTable().ajax.reload(null, false);
                },
                error: function(error) {
                    toastr.error(error.message);
                }
            });
        });
    });
</script>